### ISSUE TITLE
Weird Workaround for gh-pages

### ISSUE THREAD

**Issue by knicholes** [blue-yonder/pyscaffold#104]
Let me first thank you for this incredible project.  I'm using it for all of my new projects.

One issue I'm having is how to publish the built docs to github's gh-pages branch.  I found some [instructions](https://daler.github.io/sphinxdoc-test/includeme.html) that have me create another directory and change my conf.py to build to that dir instead, but I'm suspicious that I'm hacking around something that has already been well-thought-out and accomplished in this framework.  

Please let me know if I'm doing something weird and if there's an easier way to publish to gh-pages!

Thank you!

**Comment by FlorianWilhelm** [comment]
Hi @knicholes, thanks, we are always happy to hear that PyScaffold helps people setting up their projects more easily.

Right now there is no supported way to directly push to a `gh-pages` branch with the help of a PyScaffold template. Having browsed your instruction link, besides generating the pdf documentation in a non-default temporary directory it's only `cd $(BUILDDIR)/html; git add . ; git commit -m "rebuilt docs"; git push origin gh-pages`, right? Especially the `git add .` can potentially be dangerous or at least lead to undesired results if you forgot to commit before calling the suggested `make buildandcommithtml` command.  

This means that there is currently no easier way to do what you want to do with the help of PyScaffold and honestly I would rather not add this as an additional feature to PyScaffold directly. But with the help of @abravalheri improvements to PyScaffold's extension mechanism, it will be possible to add features like this more easily in the future. Would that help you?

Cheers!

**Comment by FlorianWilhelm** [comment]
I think this could be implemented as extension now thanks to @abravalheri's work. Therefore, I close this.
