### ISSUE TITLE
Travis install template dirties git repo

### ISSUE THREAD

**Issue by willu47** [blue-yonder/pyscaffold#107]
[Travis install script](pyscaffold/pyscaffold/templates/travis_install.template) leaves `miniconda.sh` in repository directory.

This causes issues when trying to deploy a tagged branch using dpl to PyPi on Travis, because the git repo is 'dirty'.

E.g Build [#366](https://travis-ci.org/nismod/smif/builds/268859927) checks out v0.4.4 to deploy to pypi

[running the script](https://travis-ci.org/nismod/smif/builds/268859927#L653)

[after running the travis install script](https://travis-ci.org/nismod/smif/builds/268859927#L653) the repo is tagged as 'dirty' because the `miniconda.sh` has been added to the repo.

[...causing the deploy step to fail](https://travis-ci.org/nismod/smif/builds/268859927)

**Comment by FlorianWilhelm** [comment]
@willu47 I just released version 2.5.8rc1 that you can easily install with `pip install --pre -U pyscaffold`. Please let me know if everything works for you then I will release a final version 2.5.8.

**Comment by willu47** [comment]
Tested and identified another bug in travis file.  See PR #114
