### ISSUE TITLE
Add support for GitlabCI

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#112]
Support for GitlabCI was added in PR #111 by @smartsammler. Since the inner workings of PyScaffold version 3 which is prepared on branch `v3.x` had undergone some major changes, the support of GitlabCI needs to be converted into an extension in order to make it into version 3.

**Comment by smartsammler** [comment]
Can it be an `built-in extension` or should it be realized as an external extension?

**Comment by FlorianWilhelm** [comment]
Since it seems that a lot of people are using GitlabCI I think it can be implemented as an built-in extension directly so that you could make a PR on the branch `v3.x`. What do you think @abravalheri? This would also give another opinion and feedback on @abravalheri new extension system for PyScaffold. You can easily read the documentation on how to write extension on [readthedocs](http://pyscaffold.readthedocs.io/en/v3.0a1/), since I have just released a version `v3.0a1` to make it easier.

**Comment by abravalheri** [comment]
The more feedback, the better.

Right now I am working to address the review on the extension system that
Florian did a few weeks ago, but the current implementation should be
enough (and I should be able to easily migrate the implementation to be
compliant with the last refinements suggested).

So feel free to implement it now, or wait a bit while we work on the
plumbing...
(My implementation may need to wait for #116 and #118 to be closed)

**Comment by smartsammler** [comment]
Finally I found the time to create the extension, but I have got some questions concerning consistency with the documentation:
* Should I use `structure` like it's called in the documentation or `struct` like it is in the examples (tox and travis), if one wants to also mention it as an example? Now I used `structure`.
* The documentation uses `extend_scaffold` whereas the examples use `extend_project`. I also used `extend_project`, should I stick with the documentation?

* Should I add `--with-gitlab-ci` also to the examples' section of the docu?

**Comment by abravalheri** [comment]
Hi Julian,

Regarding the name convention, I think that it is not a problem to have something slightly divergent.

I have used `structure` in the docs to make it clear, but `struct` in the code because that is what most of the existing code uses.

Do you think that `extend_project` is better than `extend_scaffold`? I can change the docs. (It is always good to have the documentation as easy to understand as possible).

Regarding `--with-gitlab-ci`, from my perspective, the more examples, the better.

**Comment by smartsammler** [comment]
Hi Anderson,

For me `extend_project` sounds better, but that's only because I think of changing my final projects being extended and not of the step between.

OK, I'll add it to the docs and create a PR.
