### ISSUE TITLE
Consider using `src` as source folder

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#115]
Currently PyScaffold creates a structure `my_project/my_package`. According to more recent versions of [setuptools](http://setuptools.readthedocs.io/en/latest/setuptools.html) a structure like `my_project/src/my_package` seems to be the preferred way.
Since we are preparing a major version 3.0 for PyScaffold we could also opt to change the current structure to the recommended one and consider it a breaking change. 
Any thoughts on this?

**Comment by abravalheri** [comment]
There are a few thoughts about it in the following post blog:

https://blog.ionelmc.ro/2014/05/25/python-packaging/

Although it is a little bit old, the selling points seems quite fair.

There is also a companion template repository in
https://github.com/ionelmc/python-nameless with a few things that can
inspire PyScaffold.

**Comment by FlorianWilhelm** [comment]
This is now in the current master for testing.
