### ISSUE TITLE
Suggestion for system tests

### ISSUE THREAD

**Issue by abravalheri** [blue-yonder/pyscaffold#120]
Right now system tests are performed in a ad-hoc fashion with a simple bash script.

A common approach to add more organization / test capabilities is to use a bash test framework like [bats](https://github.com/sstephenson/bats).

Another approach would be also using pytest with the help of some plugins such as [pytest-virtualenv](https://github.com/manahl/pytest-plugins/tree/master/pytest-virtualenv) and [pytest-shutil](https://github.com/manahl/pytest-plugins/tree/master/pytest-shutil). I personally have never used these plugins,  but if they work, keeping everything in python would be nice.

**Comment by FlorianWilhelm** [comment]
Sounds like a good idea, would [tox](http://tox.readthedocs.io/en/latest/index.html) not help regarding the virtualenv problem?

**Comment by abravalheri** [comment]
tox would definitely help. But from what I read from the documentation the pytest-virtualenv package is even more useful since it enables calling executables from a python function as if they were installed with pip.

**Comment by FlorianWilhelm** [comment]
Ah, I didn't know that, so far I have only used tox but of course we should opt for the most suitable but also reliable option.

**Comment by abravalheri** [comment]
Solved in #185
