### ISSUE TITLE
Link to `requirements depending on your Python` in `features.rst` seems to be outdated

### ISSUE THREAD

**Issue by smartsammler** [blue-yonder/pyscaffold#123]
[requirements depending on your Python](http://docs.openstack.org/developer/pbr/#requirements) in the ``features.rst`` redirects to [/pbr/latest](https://docs.openstack.org/pbr/latest/#requirements).
Is this intended or was the link directing to a more specific site in the past?

**Comment by FlorianWilhelm** [comment]
Hi @smartsammler, thanks for letting us know. The whole documentation will be reworked and PBR is about to be dropped. Checkout the branch *drop_pbr* if you want.

**Comment by FlorianWilhelm** [comment]
The docs were reworked in c4151f625ab43dea86c3bcd12a3e26938982d843. Thanks for pointing this out.
