### ISSUE TITLE
Consider MIT as license instead of New-BSD

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#126]
The MIT license is the recommended license by [choosealicense](https://choosealicense.com/) and the contrib packages `setuptools_scm` as well as `six` both use MIT. This way we could unify the number of licenses involved. As a last point, the MIT license seems to be the most prevalent license in the Python ecosystem.

**Comment by smartsammler** [comment]
choosealicense does not show New-BSD at all, but the differences are quite small so it might be a good choice considering the point of the contrib packages.
