### ISSUE TITLE
coming from Node

### ISSUE THREAD

**Issue by ORESoftware** [blue-yonder/pyscaffold#145]
Where does the putup command come from?

it's not clear where that executable comes from or how to install it

**Comment by MathMagique** [comment]
Here is where `putup` is registered as a command line script: https://github.com/blue-yonder/pyscaffold/blob/9233cd68901732fc8c1ae25f3622d3113187d015/setup.py#L25
`putup` is available after `pip install pyscaffold`.

**Comment by ORESoftware** [comment]
yeah thanks, is it not recommended to install python v3 to `python3` and pip to `pip3`?

**Comment by ORESoftware** [comment]
also, any idea why PyCharm cannot resolve the pytest dependency:

<img width="1054" alt="screenshot 2018-02-11 01 41 45" src="https://user-images.githubusercontent.com/11139560/36072002-ca2bf20c-0ecc-11e8-8234-4728ebb5058f.png">

I looked in .eggs and looks like pytest is installed, so dunno

**Comment by xhochy** [comment]
@ORESoftware no `pip3` and `python3` mostly exist on system that default to Python 2 but want also to have a co-existing Python 3 installation. Normally you work in a virtualenv created with `virtualenv`, `python(3) -m venv` or `conda create -n`; there `python` points to your selected python version (which could be any of 2.7, 2.6, 3.5, 3.6, …)

**Comment by ORESoftware** [comment]
@xhochy  thanks, yeah pycharm created a virtual env for me apparently

**Comment by FlorianWilhelm** [comment]
@ORESoftware, are your questions answered and can this issue be thus closed?

**Comment by FlorianWilhelm** [comment]
Since there was not any more activity in the last 30 days and the question seems resolved, I will close this.
