### ISSUE TITLE
Pyscaffold breaks with setuptools version 39

### ISSUE THREAD

**Issue by cpaulik** [blue-yonder/pyscaffold#148]
I get an error like

```
      File "/tmp/pip-build-gwh071/damsat/.eggs/PyScaffold-2.5.8-py2.7.egg/pyscaffold/utils.py", line 239, in check_setuptools_version
        "Your setuptools version is too old (<12). "
    RuntimeError: Your setuptools version is too old (<12). Use `pip install -U setuptools` to upgrade.
    If you have the deprecated `distribute` package installed remove it or update to version 0.7.3.
```
The reason is that `SetuptoolsVersion` was removed. See https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v3900

**Comment by FlorianWilhelm** [comment]
Thanks for reporting. That means one would need to increment the setuptools_scm version to [v1.16.0](https://github.com/pypa/setuptools_scm/releases/tag/v1.16.0) and use their fix for PyScaffold too or rather import it. I'll be only able to fix this tomorrow afternoon, but looking forward to a PR if you like to.

**Comment by cpaulik** [comment]
I really know too little to be able to make a PR quickly and I don't have time today to do the research.

**Comment by JWDobken** [comment]
The issue is not hard to solve, but you and I do not have the permission apparently.

**Comment by FlorianWilhelm** [comment]
@JWDobken, you have the permission in the sense that you can create a PR.

**Comment by JWDobken** [comment]
I have never ever done this before as well :|, soo
Please find my first open source PR #149  ever

**Comment by scorphus** [comment]
I'll create a PR to the `v2.x` branch. We still use Python 2.

**Comment by FlorianWilhelm** [comment]
Thanks a lot folks for all your support. I just pushed a version `2.5.9rc1` to PyPI, so please check if that works for you and let me know. 
@scorphus, thanks for your PR. I saw it a little late and already had something in progress which is quite similar to your solution. I added you to the list of contributors and are looking forward to more contributions from you :-)

**Comment by cpaulik** [comment]
Thanks. 

It seems to work fine.

But it means I will be upgrading and making new releases for all my older packages that are still based on pyscaffold 2.4.x. 

I'm a little annoyed by the setuptools team for removing this just for the sake of changing it to another name.

**Comment by scorphus** [comment]
YAY! 🎉 `v2.5.9rc1` works like a charm. Thanks, @FlorianWilhelm, not only for the better/more elegant solution 👍 and the new RC but also for adding me as a contributor! I look forward to contributing/learning more 🙂

**Comment by FlorianWilhelm** [comment]
Alright, after a switch to version 1.17.0 of setuptools_scm (released today) everything seems to be green again. To test everything out I released two release candidates, `v2.5.10rc1` for legacy and `v3.0.2rc3` for the current generation of PyScaffold. Please check them out and let me know if you encounter any problems.

**Comment by smartsammler** [comment]
v3.0.2rc3 works for me. Thank you for this fast release.

**Comment by scorphus** [comment]
@FlorianWilhelm, `2.5.10rc1` works well too, thanks for reacting to updates on `setuptools_scm` so quickly! 👍

**Comment by FlorianWilhelm** [comment]
PyScaffold `2.5.10` is released! I incorporated a few more changes into PyScaffold `3.0.2rc4` and give it one more day for testing.

**Comment by glebourgeois** [comment]
We tested `v3.0.2rc4` it works fine! thanks for the quick reaction, we are eager to see the final release happen :)

**Comment by FlorianWilhelm** [comment]
@glebourgeois Thanks for the feedback and the funny title of https://github.com/theQRL/QRL/issues/1046 :-)
Version `v3.0.2` was just released. Thanks to everyone in this thread for getting involved and your help!

**Comment by scorphus** [comment]
![high-five](https://media1.tenor.com/images/5fef75b9284f6d3f0a47b9eee6ce3560/tenor.gif)
