### ISSUE TITLE
Backport Sphinx 1.6 support to PyScaffold 2.5

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#152]
Right now PyScaffold 2.5.x can only handle Sphinx up to version 1.5 since there was an API change. PyScaffold 3 was changed accordingly and this change could be also back-ported to PyScaffold 2.5.x.

**Comment by cpaulik** [comment]
Is that the reason for an error like:

```
python setup.py docs
running build_sphinx
usage: usage: setup.py [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
setup.py: error: unrecognized arguments: setup.py
```

?

**Comment by FlorianWilhelm** [comment]
@cpaulik Yes, exactly. You can double check by downgrading Sphinx to version 1.5.

**Comment by cpaulik** [comment]
It works with sphinx 1.5. If you can point me to the changes that were necessary for Pyscaffold 3 then I will take a look at Pyscaffold 2.5.x. Maybe I can whip up a PR.

**Comment by FlorianWilhelm** [comment]
Thanks, it should be in file https://github.com/blue-yonder/pyscaffold/blob/14358522f4ad4c5c38a5290f8885a86bbbeb12c6/src/pyscaffold/templates/sphinx_conf.template#L44-L57 where `sphinx-apidoc` is called.

**Comment by FlorianWilhelm** [comment]
@cpaulik I added some commits to `v2.x` that updated pbr to version 4.0.2. It seems to work now, could you also check if it works for you?

**Comment by FlorianWilhelm** [comment]
@cpaulik, `v2.5.11` was just released which fixes this issue.

**Comment by cpaulik** [comment]
Thanks. Works perfectly.
