### ISSUE TITLE
Please add a --no-scm option to putup

### ISSUE THREAD

**Issue by apthorpe** [blue-yonder/pyscaffold#154]
Please allow users to decouple their projects from git, etc. by adding a `--no-scm` option to `putup` (similar to `--no-skeleton`). The problem is that unless one uses git as their SCM, `pbr` fails to get version information, `setup.py` breaks, and there's no obvious workaround. This makes PyScaffold useless to anyone using an SCM system other than git.

The most straightforward and elegant solution would seem to be to let the user manually set version information and avoid running `init_git`.

**Comment by FlorianWilhelm** [comment]
Hi Bob, which SCM are you using? If it is HG one could change PyScaffold
accordingly.
Having a scaffold without any SCM would remove quite a lot of PyScaffold's
features. For instance you would have to write a MANIFEST.in to include non
Python modules, no automatic versioning etc.
This would confuse many users I guess.

Cheers,
Florian

**Comment by apthorpe** [comment]
I'm using Mercurial; I don't know enough about setuptools_scm to write a Mercurial adapter similar to `init_git`. Even so, I'd rather manually configure `MANIFEST`, version numbering, etc. than have a broken `setup.py` with no way to fix it. PyScaffold works well for what I need - a standardized way of creating a Python project including documentation and testing.

Unfortunately, the dependency on git makes it unusable in my environment; I've spent hours trying to diagnose the `Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository.` error thrown by `pbr` - see https://stackoverflow.com/questions/49724957/how-to-use-mercurial-with-pyscaffold The amount of confusion and effort spent on trying to resolve this issue is much larger than any I would have faced had I been required to manage `MANIFEST`, version numbers, etc. manually.

Again, I'm not asking that the default behavior of PyScaffold change, just that there is an way to remove the dependency on source control left as an option for users who don't want or need the functionality.

I've made a first attempt at an extension to disable `init_git` at https://github.com/apthorpe/pyscaffold/tree/no-scm All the original PyScaffold unit tests pass and the few added for the `--no-scm` option pass as well.

I want to stress that PyScaffold is very helpful in creating a comprehensive and standard project structure. In my case, the strong coupling to git makes it much less useful than it otherwise could be.

**Comment by FlorianWilhelm** [comment]
Nice, since setuptools_scm supports Mercurial support for PyScaffold could
be added quite easily. So far I have never worked with Mercurial but I
guess it's not so difficult.

BTW, PyScaffold 3.0 and above has dropped PBR since it's main functionality
is also provided by recent setuptools versions. Do you see the same
problems also with the current PyScaffold version?

The problem with providing just the scaffold without coupling it to a SCM
is that the content of many generated files would change drastically.

Let me take a deeper look into this when I am back from vacation.

**Comment by apthorpe** [comment]
I'll look at PyScaffold 3.0 and see if that clears up problems and also look at what's in `init_git` to see if I can make a Mercurial equivalent.

You should go back to enjoying your vacation; you've given me enough to work on for awhile. 

Thanks much, :)

**Comment by FlorianWilhelm** [comment]
@apthorpe Thanks a lot! Vacation was great. Let me know if PyScaffold 3 solves your problems.

**Comment by FlorianWilhelm** [comment]
A feature like `--no-scm` is not planned to be added to core PyScaffold since too much would not work anymore. I would rather see a PR that adds Mercurial support. 
Since a `--no-scm` flag can be easily added with the help of an extension I will close this issue.
