### ISSUE TITLE
Pyscaffold and Setuptools < 30.3.0

### ISSUE THREAD

**Issue by jleni** [blue-yonder/pyscaffold#155]
When installing pyscaffold I get the following:

      File "/tmp/easy_install-c56y92hx/PyScaffold-3.0.2/setup.py", line 76, in bootstrap_cfg
      File "/tmp/easy_install-c56y92hx/PyScaffold-3.0.2/src/pyscaffold/utils.py", line 280, in check_setuptools_version
    pyscaffold.exceptions.OldSetuptools: Your setuptools version is too old (<30.3.0). Use `pip install -U setuptools` to upgrade.

Should setuptools >=30.3.0 should be included in the setup.cfg of the package?

**Comment by FlorianWilhelm** [comment]
Thank you. Not sure if there was a reason I didn't specify this dependency.
Let me check when I am back from vacation. Thanks for your PR!

**Comment by FlorianWilhelm** [comment]
Well, it definitely makes sense. It's merged. Thank you!

**Comment by jleni** [comment]
Is there any chance we could have pyscaffold 3.0.3 released with the fix?
