### ISSUE TITLE
Introduce pyproject.toml

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#167]
As the new configuration file `pyproject.toml` according to [`PEP 518`](https://www.python.org/dev/peps/pep-0518/) becomes more popular we should also support it. Currently it is not really needed, one could only add to the current default (if the file doesn't exist):
```
[build-system]
requires = ["setuptools", "wheel"]
```
add also `setuptools_scm` which is defined anyway with `setup_requires`.
@RonnyPfannschmidt has more information.

**Comment by RonnyPfannschmidt** [comment]
to sort this out, tracking a setuptools backend for pep-517 would allow to use pip for all install actions and ensuring the setup requirements nicely without ending up in a situation where one is in a "double standard situation"

**Comment by FlorianWilhelm** [comment]
This is currently solved as an external extension [pyscaffoldext-pyproject](https://github.com/pyscaffold/pyscaffoldext-pyproject). I would like to keep it like that until we see that PEP 517 really gets a high adoption, then we can move it into core PyScaffold.
