### ISSUE TITLE
Create an example repository for an extension

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#172]
Create a repository for a simple PyScaffold extension that can be used as a blueprint by others in the new [PyScaffold organisation](https://github.com/pyscaffold).
A simple extension could be one that solves #167 by adding a default `pyproject.toml`.

**Comment by FlorianWilhelm** [comment]
This was done under [pyscaffoldext-pyproject](https://github.com/pyscaffold/pyscaffoldext-pyproject). 
@abravalheri Do you want to take a look?

**Comment by abravalheri** [comment]
:+1: It seems quite nice.

Some minor comments:

- Have you used `--no-skeleton` as written in the readme or just removed the file manually? If this is the case we have to open an issue in PyScaffold (test_skeleton was generated).

- Should we generalize 'get_template' and expose it as a helper function, so it can be reused inside extensions?

**Comment by FlorianWilhelm** [comment]
@abravalheri Good point, I actually forgot to use ` --no-skeleton` and removed the file afterwards forgetting totally about `test_skeleton.py`. I fixed it. Thank you!

I think we should wait some more how people will use the extension system and if common patterns arise before we provide such a function.
