### ISSUE TITLE
Move entry_points and setup_requires to setup.cfg

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#176]
Version 3.0 of PyScaffold still has two parameters (`entry_points` and `setup_requires`) in `setup.py` instead of `setup.cfg` due to historical reasons and limitations of `setuptools` at that point. It seems now possible according to this [stackoverflow question](https://stackoverflow.com/questions/48884796/how-to-setup-entry-points-in-setup-cfg). We should thus make use of this possibility in PyScaffold version 3.1 and also move `setup_requires` to `setup.cfg` to completely get rid of any configuration in `setup.py` with the exception of Cython extensions. These will hopefully be supported in future `setuptools` version by some syntax in `setup.cfg`.

**Comment by abravalheri** [comment]
`options.entry_points` documentation can be found in [setuptools/docs/setuptools.txt#L2442](https://github.com/pypa/setuptools/blob/master/docs/setuptools.txt#L2442), and if we check the [blame](https://github.com/pypa/setuptools/blame/master/docs/setuptools.txt#L2442) of the file, this option was added to the docs in [Dec 10, 2016](https://github.com/pypa/setuptools/commit/56dea7f0334f60603d4ca6a884ca523fe3389ef3), which seems to correspond to version 38.2.5.

So we would have to change the setuptools dependency version (currently at 30.3.0)

**Comment by FlorianWilhelm** [comment]
@abravalheri, thanks for giving this a try! 

I think we might not even need `sphinx` in `setup_requires` anymore. I took this approach from the official Sphinx documentation or somewhere else quite a while ago. What we do right now in the module `integration.py` is to register the `docs` command anyway. If Sphinx is not available we register the dummy `NoSphinx` class and if a user calls `python setup.py docs` this class is called and it outputs a nice message that Sphinx is not installed. This is explicit and fine. I don't think any more that we should pull a large package like Sphinx with the help of `setup_requires` automatically. Explicit is better than implicit. 

BTW, we map the `docs` command to `build_sphinx`. In order to also show a nice error message that Sphinx is missing one would also have to register the commands `build_sphinx` and `upload_docs` to the same `NoSphinx` class with the help of a command similar to `build_cmd_docs`. So for `build_sphinx` it would actually be `build_cmd_docs` as it is for `docs` but for `upload docs` (which I have never used actually) one would need to check which class Sphinx normally registers that to.

**Comment by abravalheri** [comment]
It seems that `upload_docs` is part of setuptools directly, and it's being [deprecated](https://github.com/pypa/setuptools/blob/995d309317c6895a123c03df28bc8f51f6ead5f5/setuptools/command/upload_docs.py#L72). So I might not touch it.

**Comment by FlorianWilhelm** [comment]
@abravalheri, thanks. I think we can close this now. We should keep in mind though that we need to remove the `setup_requires` and `entry_points` parameters from `setup(...)` during an update from version 3.0 to 3.1. Let's discuss this in another issue.
