### ISSUE TITLE
Drop Python 2 support in PyScaffold v3.1

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#177]
PyScaffold is a tool for creating new Python projects and Python 3 surely has been for quite a while the right version to start a new project. Also due the a [bug](https://github.com/pypa/setuptools/issues/1136) in `setuptools` the current version 3.0 of PyScaffold has no Python 2 support right now and there were no complaints about this. 
We could officially drop the Python 2 support in PyScaffold 3.1 and get rid of `six`, unnecessary `__future__` imports in templates and the code of PyScaffold itself. This would clean things up.

**Comment by abravalheri** [comment]
To be sincere, since the test suite is intrinsically broken with 2.7, all the last changes might be incompatible  anyway...

**Comment by FlorianWilhelm** [comment]
Okay, sounds like we have a decision then ;-)

**Comment by FlorianWilhelm** [comment]
Since we have never had Python 2 support in version 3.0 we can drop it in version 3.1 officially without violating semantic version. I wouldn't want to wait for version 4.0 for that.

**Comment by FlorianWilhelm** [comment]
Since the `six` and all `__future__` imports where removed this ticket can be closed. As we go we should start using more Python 3 features and make things even more pythonic.

**Comment by abravalheri** [comment]
Unfortunately we have to wait 3.7 to be the base line to use f-strings :stuck_out_tongue_closed_eyes:
