### ISSUE TITLE
Add usage of `importlib.resources` into the docs

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#193]
For Python 3.7 `import.resources` is a better way than `pkg_resources` to load non-python files from a Python package. This should be mentioned as a modern alternative in the documentation. Since we have actually only `from pkgutil import get_data` in our documentation, it should be checked if `pkgutil` is still the way to do that at all.

**Comment by pauleveritt** [comment]
As a note, there is a backport to 3.6: https://pypi.org/project/importlib_resources/

**Comment by FlorianWilhelm** [comment]
Done in 459813ad6f6f266bd33b7ed27ce9f73b81551939.
