### ISSUE TITLE
test_update.py failing

### ISSUE THREAD

**Issue by abravalheri** [blue-yonder/pyscaffold#197]
When I try to run the test suite, but the repository is dirty, or I am some commits ahead of the commit I did `python setup.py egg_info --egg-base .` , I face an assertion error on the line 101 of `test_update.py`
```python
# ...
assert __version__ == str(self.pyscaffold_version())
# ...
```

Usually, the versions diff by a `.dirty` or `.dev<N>... != .dev<N+1>...` suffix .
The way I made it work was by running `python setup.py egg_info --egg-base .` again.
However always running this workaround can be a little bit annoying.

We could include this command in the `tox.ini`, but is it the best idea?
@FlorianWilhelm, what do you think?

**Comment by FlorianWilhelm** [comment]
Thanks for the PR! I'll look into the `test_update` issue with a dirty workspace. I think we can just use the Version object and there is some kind of method that only returns (major, minor, patch). Can I just revert to the original `tox.ini` after that?

**Comment by FlorianWilhelm** [comment]
BTW, if you pull from master, make sure you delete all egg files especially the one under src before you do `python setup.py egg_info --egg-base .` one time.

**Comment by abravalheri** [comment]
Thanks @FlorianWilhelm! Should we also discard the dev notes on `CONTRIBUTING.rst`? Or instead keep the notes there and also add your comment about deleting the egg files (it might me useful)?

**Comment by abravalheri** [comment]
After the last changes, the case when the repository is dirty was solved.
However, if the development version is commits ahead, we will also have problems.

After making a commit (changes in `tox.ini`), and running the test again, I had:

```
>       assert self.running_version.public == self.pyscaffold_version().public
E       AssertionError: assert '3.1b2.post0.dev1' == '3.1b2.post0.dev2'
E         - 3.1b2.post0.dev1
E         ?                ^
E         + 3.1b2.post0.dev2
E         ?                ^

tests/test_update.py:102: AssertionError
```

**Comment by FlorianWilhelm** [comment]
Why should we delete the dev notes? I think it is better to extend them since it helps new developers to become a contributor. 
The  `self.running_version.public == self.pyscaffold_version().public` is expected. One could use `.base_version` which would result in `3.1` but then it has almost no more information. At that point I only wanted to check that the `pytest-virtualenv` plugin does not install pyscaffold with the help of PyPI which happened a lot at first. Maybe we should just drop the assert? You could comment it out with a note if you want.

**Comment by abravalheri** [comment]
I agree in expanding the notes :)
In the open PR I have created a new troubleshooting section where we can include these kind of information and added the last comments there

If I understood it correctly, `running_version` will be the version of the source code when the developer did `python setup.py egg_info --egg-base .` and `pyscaffold_version()` will be current version of the source code (if the installation using `python setup.py develop`  behaves well). Would it work if we just compare using `<=` instead of `==`? Is it correct from the conceptual point of view? I will test this approach...

**Comment by FlorianWilhelm** [comment]
Right! Of course, using `<=` instead of `==` should do the trick! I only want to make sure that pytest-virtualenv is not pulling some officially released version von PyPI in the background and `<=` does that.

**Comment by abravalheri** [comment]
I have presented a PR for this in #199. In the end I have changed `==` to `<=`, but also included a check to see if PyScaffold installation is editable, trying to capture exactly what you have said.

**Comment by FlorianWilhelm** [comment]
Thanks a lot! This is even more robust than before. I think we can close this now.
