### ISSUE TITLE
How to control updated files in an extension?

### ISSUE THREAD

**Issue by chobeat** [blue-yonder/pyscaffold#206]
Hello guys.

To simplify my issue, what I need is to be able to update an existing template by updating exclusively the files related to my extension. For instance, I don't want to overwrite the `setup.py` because I have my entry points there. So I would like to just overwrite the files specified by my extension when I update but have a full template together with my extension when I create the project the  first time.

How to achieve that?

Thank you.

**Comment by abravalheri** [comment]
Hi @chobeat. I am not exactly sure if I understood your problem. Are those entry-points setuptools entrypoints? If that is the case, you could include them in [`setup.cfg`](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files) and the update mechanism @FlorianWilhelm have been working on should be enough to keep them after the update.

Additionally, you can try to use the [`NO_OVERWRITE`](https://pyscaffold.org/en/stable/api/pyscaffold.api.html#pyscaffold.api.helpers.NO_OVERWRITE) flag, when defining new files in the structure. The methods [`ensure`](https://pyscaffold.org/en/stable/api/pyscaffold.api.html#pyscaffold.api.helpers.ensure), [`merge`](https://pyscaffold.org/en/stable/api/pyscaffold.api.html#pyscaffold.api.helpers.merge) have support for that.

Would that help?

**Comment by abravalheri** [comment]
@chobeat, please let us know if you have any other doubts!
I hope you have a good time playing around with PyScaffold.

**Comment by FlorianWilhelm** [comment]
@chobeat, during the update the parameter `opts['update']` will be set to `True` and this `opts` dictionary of options will be passed to your extension. So based on that you can decide what to do.

**Comment by chobeat** [comment]
@FlorianWilhelm ok, this looks much more like what I need. In the following days I will try to work on this thing. Thank you again.

**Comment by FlorianWilhelm** [comment]
@chobeat Cool, I will close this for now. Just let us know if you need more help. You can also take a look into https://github.com/pyscaffold where we start to collect external extensions for PyScaffold. Right now most of them are directly inside of PyScaffold but that will change in the future. What functionality would you like to add btw?

**Comment by chobeat** [comment]
@FlorianWilhelm basically I have a custom template for my company that adds precommit hooks, bitbucket-pipelines and some other things. If I see a flaw or a possible improvement to this standard template, I would like to be able to apply it to the existing projects without having to perform any additional manual work. That's all what I'm trying to achieve. If I apply an update and this update overwrites my `setup.py` or any other file with configs (like setup.cfg, but I manage it in my extension, so it's a different case), I will have to merge them manually to avoid losing meaningful configs. For now, just skipping this step where my files gets overwritten is enough. Maybe today I will find some time to work on it.

**Comment by chobeat** [comment]
Ok, I think it's working. My function right now looks like this:

`
    def keep_on_update(self, struct, opts):
        # this function prevents undesired overwriting of files when updating existing teraki projects

        if opts["update"] is False:
            return struct, opts

        del struct[opts["project"]]["setup.py"]
        del struct[opts["project"]][".pre-commit-hooks.yaml"]
        return struct, opts`

with this in the `activate` function:

`
        actions = self.register(
                actions,
                self.keep_on_update,
                after='add_all_static')`

**Comment by abravalheri** [comment]
Hi @chobeat, nice work!

Just a minor comment that you might find useful:

If you are defining custom `setup.py` and `.pre-commit-hooks.yaml` templates (for example in `add_all_static`), you might consider something like the following approach:

```python
from pyscaffold.api import helpers

# ...

def add_all_static(self, struct, opts):
    struct = helpers.merge({
        opts['project']: {
            'setup.py': ("YOUR CONTENT GOES HERE", helpers.NO_OVERWRITE),
            '.pre-commit-hooks.yaml': ("YOUR CONTENT GOES HERE", helpers.NO_OVERWRITE),
        }
    })
    return struct, opts
```

This way, you don't need an extra action to delete the files in the structure.

By the way, @FlorianWilhelm, since now the updates are mostly handled at `setup.cfg` level, do you think it is OK to have `NO_OVERWRITE` by default on `setup.py`? I think this is welcome, for example in @chobeat  use-case, or when people are using cython.

**Comment by chobeat** [comment]
Unfortunately I'm not defining a custom setup.py: I'm fine with the default one for now. But still, the option might be useful in the future.

**Comment by abravalheri** [comment]
Well, in that case, this might work (if you are willing to avoid an extra action):

```python
struct = helpers.ensure([opts["project"], "setup.py"], update_rule=helpers.NO_OVERWRITE)
```

Let's see what Florian thinks, maybe soon this line might be the default behaviour :)

**Comment by abravalheri** [comment]
@FlorianWilhelm, do you think the use of  `helpers.{ensure, merge}` doesn't help? If I remember it correct, both functions will handle content/flags accordingly. So for example, if you pass just the content, but the old entry has flags, the old flags are kept. If you pass just the flags (`None` for content), the old content is preserved...

Well, we could for sure make everything tuples by default, but I am just not exactly sure if that is the right abstraction. For some time I thought in functions...

Another thing to consider is that sometimes, the current behavior is welcome... For example, if the person just want to change the content of a file, this person can do that very easily, without having to dig into the documentation/code to look for the right flags:

```python
struct = helpers.merge({
    opts['project']: {
        'README.rst': 'NEW CONTENT'  # Old flags preserved
    }
})
```

**Comment by FlorianWilhelm** [comment]
@abravalheri, if you want to you could take a look at the pyscaffoldext-markdown extension. My use case there was that I wanted to add a few lines to `conf.py` and also run ConfigUpdater on `setup.cfg`. When traversing the struct I had to make always sure if I am dealing with a tuple or the actual content when I wanted to change something.

**Comment by FlorianWilhelm** [comment]
If we had a function like this I think that would be better. Then no one would have to deal with the structure itself. Cool! Should we then postpone the release until we have it in there?
