### ISSUE TITLE
Change helpers to use pathlib.Path

### ISSUE THREAD

**Issue by abravalheri** [blue-yonder/pyscaffold#211]
In the past when introducing the extensions API, one point that was controversial was the usage of either lists of file path parts or strings using the forward slash as separator for `helpers.ensure` and `helpers.reject`.

It was suggested that we could use `pathlib.Path` to simplify the code.

Now that we run on Python 3 and `pathlib` is part of the standard library we can discuss more about that.

Since it breaks the API, if we go for this approach, we would have to start deprecating it now so we can include it in the next major release.

**Comment by abravalheri** [comment]
If we decide to adopt the new behaviour:

v3.2 - Deprecation Notice
v4.0 - Actual change

**Comment by FlorianWilhelm** [comment]
@abravalheri Sounds like a great idea. Since it was included in Python 3.4 we should do it as you said. Thanks!

**Comment by abravalheri** [comment]
Implemented in #215 with deprecation notices.
TODO note added explaining how to drop support for lists/tuples in v4.
