### ISSUE TITLE
Coverage fails in new projects

### ISSUE THREAD

**Issue by chobeat** [blue-yonder/pyscaffold#213]
Hello guys,

when running `python setup.py test` the following error is raised in projects using the default template

`Coverage.py warning: Module my_module was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)
 
ERROR: Failed to generate report: No data to report.` 

It's clearly related to coverage run through pytest but I'm not sure how to fix. This is the .coveragerc

https://gist.github.com/chobeat/35037bbcdf634f20fbad10edf46a8d3b

**Comment by FlorianWilhelm** [comment]
@chobeat Are you using the current master, version 3.1rc1 or 3.0.3?

**Comment by chobeat** [comment]
3.0.3

**Comment by FlorianWilhelm** [comment]
@chobeat, could you test with the current master branch? @abravalheri fixed some things and maybe that was one of the problems.

**Comment by FlorianWilhelm** [comment]
@chobeat You can also tried the latest release candidate with `pip install --pre --upgrade pyscaffold`.

**Comment by chobeat** [comment]
The error is still thereu with 3.1rc2. Tell me if you can reproduce it. It happens in Docker, local environment and bitbucket environment, so I guess it's not due to my setup.

**Comment by chobeat** [comment]
Ok, I'm sorry. It happens only with the `--no-skeleton` option. It makes sense: it has no tests and so it fails. Then probably there must be some issue in the import of the projects where I see these errors that was introduced by me. Thank you.

**Comment by abravalheri** [comment]
BTW @FlorianWilhelm, I think I need to update the `.coveragerc` template again to match PyScaffold's own, I did updated it in the open PR, but I don't think it is getting merged right?

**Comment by FlorianWilhelm** [comment]
@abravalheri, ah right! Thanks, could you update it?

**Comment by abravalheri** [comment]
Done, @FlorianWilhelm.

Something that I have not done is including the `coverage combine` in the template for `.travis.yml`, because I understand we are not encouraging the workaround for the generated projects, but instead waiting for pytest-cov to fix this in the next release, right?
