### ISSUE TITLE
API documentation is not being compiled for latest on RTD

### ISSUE THREAD

**Issue by abravalheri** [blue-yonder/pyscaffold#214]
For some reason the module documentation (autodoc) is not being generated for `latest`:
https://pyscaffold.org/en/latest/api/pyscaffold.api.html

`stable` is fine though:
https://pyscaffold.org/en/stable/api/pyscaffold.api.html

**Comment by FlorianWilhelm** [comment]
Hm... strange.. does RTD show any hints? Does it work locally? Maybe a regression since 3.0.3

**Comment by FlorianWilhelm** [comment]
I tried to reproduce the problem locally but failed. If you check RTD you see that in the installation step we have:
```
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing UNKNOWN.egg-info/PKG-INFO
writing entry points to UNKNOWN.egg-info/entry_points.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
```
Somehow during the installation Sphinx cannot determine the name of the package from `setup.cfg` although it should. This then causes it to not find the appropriate modules for the API reference. It also seems to forget about the `src`-layout. I tried a few things on to `dev` branch by reverting some things back to the setup.py version in v3.0.3 but in vain.

**Comment by FlorianWilhelm** [comment]
Okay, solved it after many tries. RTD seems to be extremely stateful and whenever something doesn't work it's best to first wipe the whole setup by clicken Versions -> Edit -> Wipe. That solved it in the end.

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm!
