### ISSUE TITLE
Support both python2.7 and python3.6

### ISSUE THREAD

**Issue by Ublimjo** [blue-yonder/pyscaffold#217]
## How can I write code that supports both python2.7 and python3.6 ?
Since pyscaffold v3.1 python2.7 supports is dropped

I want to use pyscaffold 2.5 and pyscaffold 3.2 inside setup.py

```python
if sys.version < (3, 0):
    # ....
```

**Comment by FlorianWilhelm** [comment]
Following information is important for the answer. Do you want to
1. develop code with Python 3 only but the code will be released with PY2/3 support using six maybe,
2. develop code with Python 2 and Python 3?

In case of 1. you could just use PyScaffold 3.1 and do your thing in Python 3. If you distribute your package as `bdist_wheel` there will be no dependency whatsoever to PyScaffold and thus it will be as compatible as you made it. In case of 2, I currently see only the possibility of staying with PyScaffold 2.5. There were just too many major changes in PyScaffold 3 and thus switching from 2 to 3 depending on Python version would most likely mess everything up.

**Comment by FlorianWilhelm** [comment]
I have added you question to the [FAQ](https://pyscaffold.org/en/latest/faq.html).

**Comment by Ublimjo** [comment]
Ok, it's clear
