### ISSUE TITLE
Check necessity of Manifest.in

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#33]
With https://docs.python.org/2/distutils/sourcedist.html#manifest and https://docs.python.org/2/distutils/setupscript.html#installing-additional-files it should be possible to completely avoid a custom `MANIFEST.in`. Check that and implement if positive.

**Comment by FlorianWilhelm** [comment]
By using `data_files` it is possible to drop `MANIFEST.in`. Since the need to specify files for a source-distribution in `MANIFEST.in` but not for a binary-distribution is confusing we just avoid it.

**Comment by sebastianneubauer** [comment]
What does it mean now? Do you mean it's possible to drop Manifest.in? I don't think so, at least I never got it working without...

**Comment by FlorianWilhelm** [comment]
@sebastianneubauer It means that MANIFEST.in is not really necessary. As the link https://docs.python.org/2/distutils/setupscript.html#installing-additional-files shows, starting from Python 2.7, you can provide additional files with the `data_files` parameter. This is much more concise since then also bdist and bdist_wheel will make use of these additional information. I dropped MANIFEST.in in some of the last commits and it seems to work. Now there is only one place, setup.cfg, that you need to touch in order to configure your package.
