### ISSUE TITLE
Allow package_data to be specified in setup.cfg

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#36]
It should be possible to define additional data (non-python files) in `setup.cfg`. distutils supports this with `data_files` and `package_data`. It seems setuptools especially features `package_data` so this should be used maybe in a seperate [package_data] section in `setup.cfg`. Here is the introduction:
https://pythonhosted.org/setuptools/setuptools.html#including-data-files

**Comment by fruch** [comment]
+1
I was trying to package this with stdeb, and it failed on exactly that (looking for the README.rst)

**Comment by FlorianWilhelm** [comment]
@fruch Thanks for your input. Could you explain a little bit more what you did and how? README.rst should be already included by MANIFEST.in but I have never used stdeb so far.

**Comment by fruch** [comment]
You are correct it was my mistake not updating the manifest. Sorry.
