### ISSUE TITLE
Consider usage of setuptools-git

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#38]
Using setuptools-git would allow to use the `include_package_data` keyword argument for `setup`. The downside would be an additional dependency as well as the need to add the `exclude_package_data` keyword.

**Comment by HolgerPeters** [comment]
Not quite sure if this really improves upon the current situation.

**Comment by FlorianWilhelm** [comment]
@HolgerPeters I am also skeptical but a lot of users seem to use `setuptools-git` judging from the number of downloads on pypi. It is also possible to support it without introducing a hard additional requirement. With the help of `setuptools.dist.Distribution` and its method `fetch_build_eggs`, it is possible to do that on the fly if someone wants to use the feature. What do you think?

**Comment by HolgerPeters** [comment]
Can you find an up to date git repository for this? pypi links to https://github.com/wichert/setuptools-git and that redirects to https://github.com/msabramo/setuptools-git it seems. Has not seem much work lately.

**Comment by FlorianWilhelm** [comment]
@HolgerPeters I just found a huge issue with `setuptools-git` when working with source distributions and `pip` which is a quite common combination. While the sdist distribution is packaged correctly when `include_package_data` is true and `setuptools-git` is installed, the package data is not correctly unpacked and put into the virtual environment. It fails because `pip` unpacks the sdist tarball, and runs `setup.py`. At that time we are no longer in a git repository, so the `include_package_data` command does not seem to know what to do with the additional data files and ignores them. At least this is how I understand it. Btw. Also `exclude_package_data` does not really work as I would expect it. So the best way it seems is to explicitly state what extra data files you want to include.
