### ISSUE TITLE
Consider usage of setuptools-scm

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#43]
This tools seems to do a lot of what versioneer does and could possible drastically reduce the code in setup.py.

**Comment by ManuelBahr** [comment]
Hey we would attempt to fix this during our blue yonder hackathon. Is it ok, or have you started already?

**Comment by xhochy** [comment]
Nothing really started yet, so feel free to fix it.

**Comment by FlorianWilhelm** [comment]
@PhilipHauber You also worked at this, right? Got a branch of your changes somewhere that I could look into?

**Comment by FlorianWilhelm** [comment]
After some hacking and help from Ronny Pfannschmidt, the creator of [setuptools_scm](https://pypi.python.org/pypi/setuptools_scm/), I think all reminiscents of Versioneer are now replaced.
