### ISSUE TITLE
Checkout usage of nose as testrunner

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#44]

**Comment by HolgerPeters** [comment]
Is there an added benefit that nose provides? In my perception, pytest is the more modern and more feature rich test suite. I submitted a pull request to matplotlib trying to introduce a `python setup.py test` command, based on their nosetests setup, and they are going through all kinds of trouble with pretty standard test stuff (like a hand written `KnownFailure` plugin for expected failures).

**Comment by StephanErb** [comment]
The ultimate motive is to get rid of the custom test runners in pyscaffold. I proposed nose, but there are probably other ways to achieve this (e.g., https://pypi.python.org/pypi/pytest-runner).

**Comment by FlorianWilhelm** [comment]
@StephanErb that sounds like a good solution. So no nosetest but pytest-runner instead, I'll create an issue.

**Comment by FlorianWilhelm** [comment]
I created the issue #47.
