### ISSUE TITLE
Allow Cython files to be included

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#48]
Right now PyScaffold does not directly allow to create packages which use Cython files. This functionality of setuptools is not yet exposed in a user-friendly way. We should start collecting ideas how we could resolve this.

**Comment by HolgerPeters** [comment]
The implementation of Cython building is kind of complicated. As I recall, Cython extensions are based on the C extensions of setuptools which in turn are distutils extensions.  https://docs.python.org/2/extending/building.html I.e. to compile a cython file right now, you create an `Extension` object in your `setup.py`, specifiying path of the source file, and other parameters needed for the Compilation of the C code.

Now, if we want to improve upon the situation of manually adding Extensions to the setup.py (which is how we use Cython and pyscaffold at the moment), pyscaffold should offer some automaticism. Pyscaffold's setup.py could possibly scan the directory tree for pyx and pxd files and add those as Cython extensions programmatically, this approach fails as soon as more configurations like include_dirs, or libraries have to be specified (http://docs.cython.org/src/reference/compilation.html#configuring-the-c-build). This means however, that in some why pyscaffold's setup.py would have to find some annotation telling which include dirs, flags, etc. should be modified for certain files. In the end you might end up with pyx/pxd autodiscovery which is paraphrased by more flags and settings for each and every file. Thus I would say an autodiscovery will not necessarily simplify the usage of Cython.

Did you have an idea in mind how to make Cython usage easier with PyScaffold?

**Comment by FlorianWilhelm** [comment]
Rather than going into into the direction of complete automation, I would like to expose the parameters of `Extension` objects in a structured way inside `setup.cfg`. I am just not sure what the best way is since I am lacking the experience with Cython. @HolgerPeters Could you imagine a declarative way of defining the extensions for your projects inside `setup.cfg`?

**Comment by FlorianWilhelm** [comment]
Looking at the source code of ```pbr/util.py```, it seems exactly this functionality is already implemented. The syntax for ```setup.cfg``` is:

> [extension:ext_name]
> sources=
> include_dirs=
> define_macros=
> undef_macros=
> library_dirs=
> libraries=
> runtime_library_dirs=
> extra_objects=
> extra_compile_args=
> extra_link_args=
> export_symbols=
> swig_opts=
> depends=

Needs to be tested though and then documented.

**Comment by HolgerPeters** [comment]
it is not that easy unfortunately. For example we have to obtain `include_dirs` programatically, so we could not just specify our Cython extensions in the setup.cfg.

**Comment by FlorianWilhelm** [comment]
@HolgerPeters How do you do that? Is this some kind of ``finde_include_dirs`` function that a library provides or home-brew?

**Comment by HolgerPeters** [comment]
For example like in `include_dirs = [numpy.get_include()])`

**Comment by FlorianWilhelm** [comment]
I filed a bug report in the PBR launchpad:
https://bugs.launchpad.net/pbr/+bug/1510898

**Comment by FlorianWilhelm** [comment]
If we drop pbr the default methods of including cython files could be used again directly within `setup.py`. I would prefer a more declarative way with `setup.cfg` but this seems to be as good as it gets right now.

**Comment by t184256** [comment]
FYI, this is how it should've been done with `pbr`:

```
[build_ext]
pre-hook.include_numpy = setup_hooks.include_numpy
```

```
def include_numpy(cmd):
     '''Add numpy include dir for all extensions, see setup.cfg'''
     import numpy
     for extension in cmd.extensions:
         extension.include_dirs.append(numpy.get_include())
```

**Comment by t184256** [comment]
```
[entry_points]
console_scripts =
    pbr = pbr.cmd:main
pbr.config.drivers =
    plain = pbr.cfg.driver:Plain
```

`pbr` has it.

My point was that maybe dropping `pbr` wasn't a good idea. It does a lot of things just right.

**Comment by FlorianWilhelm** [comment]
Got it but setuptools is the standard and will most likely integrate more
and more of pbr's feature. Also, having read a lot of pbr's source code it
looked like a big mess to me...

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, do you think there is any way of adding a layer on top of [setuptools `parse_configuration`](https://github.com/pypa/setuptools/blob/master/setuptools/config.py#L93)?

If that is the case, we could hijack the options after they are parsed, transform them and then apply the arguments back to the `setup` function...

I am just wondering if this is possible/easy. The main point is that, if an user of PyScaffold include Cython extensions directly to `setup.py`, and afterwards decide to update the project to the latest version of PyScaffold using `putup --update`, all the work will be lost...

**Comment by FlorianWilhelm** [comment]
Hi @abravalheri, I think it would be possible since PBR was doing something like that too. Since this would mean doing monkey-patching and other sorts of black magic, we should refrain from implementing something like that and wait for `setuptools` to come up with support for this in `setup.cfg`. Since really only a small number of Python experts uses Cython at all, I think it's okay to let them define their Cython builds in `setup.py`.
