### ISSUE TITLE
Better default README.rst

### ISSUE THREAD

**Issue by StephanErb** [blue-yonder/pyscaffold#51]
Many users of pyscaffold tend to keep the default README.rst.  Unfortuantely, this readme is tailored for the user of pyscaffold but not for any user of the project, who only wants to find out what the project does and how it can be run/tested. 

The readme should therefore be shorter and more to the point without any long explanations. It could also contain an elevator pitch of the project.

**Comment by MatthiasBach** [comment]
Yes, I think something along the lines of "This project has been set up using pyscaffold. For details and usage information on pyscaffold see https://github.com/blue-yonder/pyscaffold." would be good. The remaining content of the README.rst should then be added to pyscaffold's README.md. Alternatively it could be stored in a HOWTO.md.

**Comment by FlorianWilhelm** [comment]
Thanks for reporting. I used a variant of the wording of @MatthiasBach.
