### ISSUE TITLE
Avoid `__init__.py` in tests directory

### ISSUE THREAD

**Issue by HolgerPeters** [blue-yonder/pyscaffold#52]
The pytest docs (https://pytest.org/latest/goodpractises.html) advice to not put an `__init__.py` file into the tests directory:

> avoid “__init__.py” files in your test directories. This way your tests can run easily against an installed version of mypkg, independently from the installed package if it contains the tests or not.

**Comment by FlorianWilhelm** [comment]
@HolgerPeters Good point, thanks, are you up for a PR?

**Comment by HolgerPeters** [comment]
yes I am, probably not this week though.

**Comment by HolgerPeters** [comment]
I suggest replacing `__init__.py` by a `conftest.py` (https://pytest.org/latest/plugins.html) if the directory `tests` would be empty, it would not persist in git - and adding a conftest.py seems better than checking in a `.dummy.txt`

**Comment by FlorianWilhelm** [comment]
Yes, sounds like a good plan.

**Comment by FlorianWilhelm** [comment]
@HolgerPeters Your PR was merged and a dummy ``conftest.py`` file is created with a bit of information about it.
