### ISSUE TITLE
Migration from docs/changes.rst to CHANGES.rst on --update does not copy the content

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/pyscaffold#54]
Updating my project to the latest git revision of PyScaffold will delete `docs/changes.rst` and create a new `CHANGES.rst` with dummy contents. In an update it would be better to just copy the contents to the new place.

**Comment by FlorianWilhelm** [comment]
The files `docs/changes.rst` and `CHANGES.rst` were both introduced in version 2.1. I assume you had your own `docs/changes.rst` before that and during the update it was replaced by the new content. With the help of some git magic it should be no problem to move the content from your old `docs/changes.rst` file into `CHANGES.rst`:
 > git show HEAD^:docs/changes.rst > CHANGES.rst
