### ISSUE TITLE
Add a version requirement for setuptools

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/pyscaffold#56]
Installing PyScaffold warns about an outdated version of setuptools. Instead it should just depend on a newer version.

```
your setuptools is too old (<12)
setuptools_scm functionality is degraded
```

**Comment by FlorianWilhelm** [comment]
From commit 1ef0a904e180dcccc70890347c0d704fc5e19768 onwards, Pyscaffold as well as projects created with it will require at least `setuptools>=9.0`.
