### ISSUE TITLE
Provide proper defaults for `devpi upload`

### ISSUE THREAD

**Issue by MatthiasBach** [blue-yonder/pyscaffold#62]
PyScaffold should provide proper defaults for the [`devpi upload`](http://doc.devpi.net/latest/userman/devpi_commands.html#upload) as the usage of [https://pypi.python.org/pypi/setuptools_scm](https://pypi.python.org/pypi/setuptools_scm) comes with some peculiarities in combination with `devpi upload`. E.g. devpi by default exports from the SCM to avoid packaging files not under version control.

Potential content of the relevant section in `setup.cfg`could be:

    [devpi:upload]
    formats = sdist.tgz,bdist_wheel
    no-vcs = 1
    with-docs = 1

Rational for each line:
* setuptools_scm is a required to execute the setup.py and installation will be handled by easy_install. As this can cause errors when using custom indices a wheel should be provided.
* no-vcs ensures that the version console information is present during packaging.
* with-docs would ensure the documentation is also uploaded to devpi. As PyScaffold generates Sphinx documentation I assume this to be a sensible default.

**Comment by StephanErb** [comment]
Slight correction: `with-docs` is not supported. Only `formats` and `no-vcs` are applicable.

See: https://bitbucket.org/hpk42/devpi/src/2baae00d35df81608edc5705215ad72986436fab/client/devpi/upload.py?at=default#cl-32 and the following lines

**Comment by FlorianWilhelm** [comment]
Thanks. This is addressed in v2.3rc11.
