### ISSUE TITLE
Unable to Include Data Files

### ISSUE THREAD

**Issue by trent** [blue-yonder/pyscaffold#64]
I've added a foo.json file to the root of my scaffold project and updated the `[data_files]` section to include `*.json`.  When I run `python setup.py sdist`, foo.json is not included in my package.  Am I missing some other setting necessary to include arbitrary files?

**Comment by trent** [comment]
So, I was able to get this to work if I add a MANIFEST.in that includes foo.json, but this goes against what the setup.cfg says about MANIFEST.in not being needed anymore.

**Comment by trent** [comment]
I figured it out.  You have to have foo.json committed to the repo before creating the distribution.d

**Comment by FlorianWilhelm** [comment]
@trent Thanks for reporting this anyway, I'll add a few extra lines to the documentation.
