### ISSUE TITLE
Cannot install: missing pbr_json

### ISSUE THREAD

**Issue by vincent-legoll** [blue-yonder/pyscaffold#67]
Hello I'm trying to install pyscaffold on ubuntu 14.04, but it's failing:

<pre>
# pip install --upgrade pyscaffold
Downloading/unpacking pyscaffold
  Downloading pyscaffold-2.4.1.tar.gz (108kB): 108kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pyscaffold/setup.py) egg_info for package pyscaffold
    
    Installed /tmp/pip_build_root/pyscaffold/.eggs/pbr-1.7.0-py2.7.egg
    Searching for setuptools-scm<1.8a0,>=1.7
    Reading https://pypi.python.org/simple/setuptools_scm/
    Best match: setuptools-scm 1.7.0
    Downloading https://pypi.python.org/packages/source/s/setuptools_scm/setuptools_scm-1.7.0.tar.gz#md5=d0423feeabda9c6a869d963cdc397d64
    Processing setuptools_scm-1.7.0.tar.gz
    Writing /tmp/easy_install-eGkpOz/setuptools_scm-1.7.0/setup.cfg
    Running setuptools_scm-1.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-eGkpOz/setuptools_scm-1.7.0/egg-dist-tmp-S78qmF
    Moving setuptools_scm-1.7.0-py2.7.egg to /tmp/pip_build_root/pyscaffold/.eggs
    
    Installed /tmp/pip_build_root/pyscaffold/.eggs/setuptools_scm-1.7.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pyscaffold/setup.py", line 139, in <module>
        setup_package()
      File "/tmp/pip_build_root/pyscaffold/setup.py", line 135, in setup_package
        'local_scheme': local_version2str})
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 12, in replacement_run
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
        return self.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named pbr_json
    Complete output from command python setup.py egg_info:
    

Installed /tmp/pip_build_root/pyscaffold/.eggs/pbr-1.7.0-py2.7.egg

Searching for setuptools-scm<1.8a0,>=1.7

Reading https://pypi.python.org/simple/setuptools_scm/

Best match: setuptools-scm 1.7.0

Downloading https://pypi.python.org/packages/source/s/setuptools_scm/setuptools_scm-1.7.0.tar.gz#md5=d0423feeabda9c6a869d963cdc397d64

Processing setuptools_scm-1.7.0.tar.gz

Writing /tmp/easy_install-eGkpOz/setuptools_scm-1.7.0/setup.cfg

Running setuptools_scm-1.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-eGkpOz/setuptools_scm-1.7.0/egg-dist-tmp-S78qmF

Moving setuptools_scm-1.7.0-py2.7.egg to /tmp/pip_build_root/pyscaffold/.eggs

Installed /tmp/pip_build_root/pyscaffold/.eggs/setuptools_scm-1.7.0-py2.7.egg

running egg_info

creating pip-egg-info/pyscaffold.egg-info

writing requirements to pip-egg-info/pyscaffold.egg-info/requires.txt

writing pip-egg-info/pyscaffold.egg-info/PKG-INFO

writing top-level names to pip-egg-info/pyscaffold.egg-info/top_level.txt

writing dependency_links to pip-egg-info/pyscaffold.egg-info/dependency_links.txt

writing entry points to pip-egg-info/pyscaffold.egg-info/entry_points.txt

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pyscaffold/setup.py", line 139, in <module>

    setup_package()

  File "/tmp/pip_build_root/pyscaffold/setup.py", line 135, in setup_package

    'local_scheme': local_version2str})

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "<string>", line 12, in replacement_run

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load

    return self.resolve()

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

ImportError: No module named pbr_json

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pyscaffold
Storing debug log for failure in /home/vlegoll/.pip/pip.log
</pre>

**Comment by vincent-legoll** [comment]
pip install --upgrade pbr

fixed the issue (need more coffee)

**Comment by vincent-legoll** [comment]
I was about to suggest putting that into requirements, but it's already there...
I'm obviously missing something, sorry for the noise

**Comment by FlorianWilhelm** [comment]
Hi @vincent-legoll, would be interesting to know your ``setuptools`` and ``pip`` version. Normally pip should figure this out automatically.

**Comment by vincent-legoll** [comment]
I was on system's owned versions:
- python-setuptools (3.3-1ubuntu2)
- python-pip (1.5.4-1ubuntu3)

but then did:
<pre>
# pip install --upgrade setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-18.3.1-py2.py3-none-any.whl#md5=a21a4d02d0bab2eac499cca72faeb076
  Downloading setuptools-18.3.1-py2.py3-none-any.whl (462kB): 462kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed setuptools
Cleaning up...
</pre>
Don't ask me why I'm still on such an old distro...

**Comment by FlorianWilhelm** [comment]
That really is quite old but since Ubuntu 14.04 is an LTS release, it's completely understandable. My PC at my working place even runs the old LTS 12.04. 
My first command after `virtualenv` always is `pip install -U setuptools pip`.  With a newer pip version you also get the newish `pip list` command which is much more human-readable than `pip freeze`. The packages `setuptools` and `pip` are special btw in the way that you can't just specify in the requirements that your package needs `setuptools>=12`, it will just be ignored.

**Comment by vincent-legoll** [comment]
Yeah, you're right I really should start to use virtualenv a lot more...

**Comment by danielsouzasp** [comment]
Thanks Vicent.
