### ISSUE TITLE
Be less restrictive on pbr versions

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/pyscaffold#69]
Currently the pbr version is strictly pinned on the minor version. This prevents me from installing packages that depend on different pyscaffold versions, i.e. I cannot have a package setup with PyScaffold 2.3 and one with PyScaffold 2.4.1 in my virtualenv. To solve this problem, PyScaffold should specify only the minimum required version in its dependencies.

**Comment by FlorianWilhelm** [comment]
Thanks for pointing this out. Since especially pbr caused already a lot of trouble I wonder if it would be better to include setuptools_scm and pbr directly into Pyscaffold as contrib subpackages. That would resolve it. What's your opinion on that @xhochy.

**Comment by xhochy** [comment]
While I dislike contrib packages as you need to extra careful in updating them, in this case it seems like the correct solution. (I'd love to have some npm-style packaging here where you can have different versions of a packages installed in the same project).
