### ISSUE TITLE
Setup and Test Requirements considered harmful

### ISSUE THREAD

**Issue by HolgerPeters** [blue-yonder/pyscaffold#71]
Currently the setup.py that pyscaffold generates contains these lines:
```
    setup(setup_requires=['six', 'pyscaffold>=2.4rc1,<2.5a0'] + sphinx,
          tests_require=['pytest_cov', 'pytest'],
```
usage of `setup_requires` and `tests_require` is unfortunately a little problematic. Setuptools/distutils will install the packages listed there into the `.eggs` directory upon calling `python setup.py develop` and `python setup.py test`. Since the introduction of virtualenvs in the python workflows, one is probably more interested to use one virtualenv for developing and building the tool, and another one for running the tool that does not include the dev requirements.

**Comment by sebastianneubauer** [comment]
+1 the whole approach seems to be screwed at the moment and we need to find a way to fix it...

**Comment by HolgerPeters** [comment]
To be fair, `setup_requires` and `tests_require` are the way that setuptools/distutils are layed out.

**Comment by FlorianWilhelm** [comment]
Hm... but `setup_requires` is actually needed for the whole concept of tools like PyScaffold, setuptools_scm and pbr. Can you elaborate some more where the problem is? Is it directly connected to #70 ?

**Comment by HolgerPeters** [comment]
Let's separate two things, for one, what we would like to have, and then what setuptools does and how this differs from what we would like to have in an environment where we use virtualenvs:

What we want: we would like to have a way to specify dependencies that we only need for executing a setup.py and not during runtime.

What setuptools offers: Setup requirements can be specified and are installed in a `.eggs` directory in the project. They appear as if they were installed and interfere with the state of the virtualenv (or the system python packages if no virtual env is used). In my experience, having packages in `.eggs` directory is a typical cause for trouble.

Nowadays, we have virtualenvs, so what we want is, to install all packages we need during development into a development virtualenv. We build a wheel for packaging our package up and install it in another, fresh virtualenv that does not pull any setup requirements for running the software. Virtualenvs enable us to not use the `.eggs` directory.

My workflow involves having a `dev_requirements.txt` file in the repo that I just install into the environment I am developing in. This means that I have to execute one `pip install -r dev_requirements.txt` before I can execute the setup.py, but ensures that `.eggs` will not trouble me.

## Example

What kind of trouble is it when packages are installed in a .eggs directory?

```
% putup asdf
% cd asdf
% pip install -e .
%  % python setup.py test
running test
Searching for pytest
Reading https://pypi.python.org/simple/pytest/
Best match: pytest 2.7.3
[snip]
Installed /............/asdf/.eggs/pytest-2.7.3-py2.7.egg
[snip]
% py.test
pyenv: py.test: command not found
```
So I will go on and install pytest in my virtualenv. No I have two pytest installations.

**Comment by FlorianWilhelm** [comment]
@holgerpeters, good explanation. So when everything is already in your virtual environment, it should be no problem. It only causes trouble if setuptools installs software into the egg folder that was not available before. The question is if setuptools allows changing from easy_install to pip. Another option would be to raise an error for at least all packages in setup_requires instead of installing them with the help of setuptools. 
I am looking forward to your thoughts on that @holgerpeters and @sebastianneubauer.

**Comment by FlorianWilhelm** [comment]
After our discussion, several things will be done to avoid this issue. First of all #72 will limit those possible conflicts to PyScaffold itself. Then avoiding `test_requires` and using an `test-requirements.txt` file like in #70 should at least limit the number of eggs you'll have if you set up your venv beforehand.
