### ISSUE TITLE
Remove option for --with-numpydoc and permanently add sphinxcontrib napoleon

### ISSUE THREAD

**Issue by HolgerPeters** [blue-yonder/pyscaffold#74]
Sphinx has now builtin support for Numpy-style docstrings via http://sphinx-doc.org/latest/ext/napoleon.html . So I propose that we drop the `--with-numpydoc` option from pyscaffold altogether and -- by default -- add sphinx.ext.napoleon to the list of extensions in `docs/conf.py`

**Comment by FlorianWilhelm** [comment]
Sorry, couldn't resist, does commit 15e7a4cdacd081711697c89459ccddd239314acd do what you want?

**Comment by HolgerPeters** [comment]
It is kind of what I was already preparing...

**Comment by FlorianWilhelm** [comment]
@HolgerPeters, thanks, then I take that as a yes. Sorry, if that caused double work.
