### ISSUE TITLE
support for virtualenv?

### ISSUE THREAD

**Issue by jvsteiner** [blue-yonder/pyscaffold#95]
does it exist?  would think automatically adding a virtualenv (and associated entry to .gitignore) would be a helpful addition.  Any plans/desire to add this?

**Comment by HolgerPeters** [comment]
The tox support gives you a virtual environment for tests already (which is of course not a virtual environment in the classical sense).

In my experience, virtualenvs need to be created and to be disposed of rather frequently. By automatically creating one, the effort is reduced exactly one time. I am not sure if we want to automatize a regular process just by one time.

I would probably rather see pyscaffold incorporate a pip-tools workflow (pip-compile, pip-sync) which would make recreating virtual environments cheaply.

Let's see what Florian thinks about this.

**Comment by FlorianWilhelm** [comment]
I agree with @HolgerPeters and want to add that the focus of PyScaffold is to provide a template for a Python project, nothing less but also nothing more. You can easily create and provision a virtualenv with the help of the generated ``requirements.txt`` file and ``pip``.
Additionally, I am not 100% convinced that a virtualenv should reside inside the project's directory. For my part, I always use [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/) that creates the virtual environments in ``~/.virtualenvs``. To be really honest, in the last couple of weeks I even started to bed [conda](http://conda.pydata.org/) which does a similar thing. Therefore, I don't think it is in the best interest of the majority of PyScaffold's userbase to have an empty virtualenv named ``venv`` after having called ``putup``.
