### ISSUE TITLE
Pytest deprecation

### ISSUE THREAD

**Issue by willu47** [blue-yonder/pyscaffold#96]
`[pytest]` heading in setup.cfg is deprecated in latest version of pytest, and should be `[tools:pytest]`

**Comment by FlorianWilhelm** [comment]
Thanks @willu47 for pointing out, I already corrected this in commit 69e6c06a4229308efc3a5ff4aa45eb6db3a26461 in the development branch a while ago. I think it's about time to make a new release soon. I am just waiting for the PR of @girstenbrei .

**Comment by girstenbrei** [comment]
Thanks @willu47 , I also noticed the deprecation warning. @FlorianWilhelm , right now, I am in the middle of my uni-tests (bad timing, as if they jumped out behind a corner :) ), so I have to do the pull request after finishing them (I think, 2 weeks is doable for me). Just fyi, if you want to release earlier.

**Comment by FlorianWilhelm** [comment]
I will also work on some small changes that I want in the next release. If I get this done in the next few days I will release a bugfix release and we push your changes @girstenbrei in the next minor release.

**Comment by FlorianWilhelm** [comment]
I just released version 2.5.7 which should fix the issue. Thanks again @willu47 for filing this issue.
