### ISSUE TITLE
not updating newly added modules and remove removed ones

### ISSUE THREAD

**Issue by enfeizhan** [blue-yonder/pyscaffold#98]
I am currently using pyscaffold 2.5.7 and sphinx 1.4.9.  Found two maybe "issues", firstly documentations for removed modules still exist e.g. in html files. It doesn't find the changes also the other way, newly added modules don't show up in htmls.

Wondering is this supposed to be so or I am not doing it correctly? Let me know if you need more info to identify any issue. Thanks!

**Comment by enfeizhan** [comment]
Or this is actually a sphinx issue?

**Comment by enfeizhan** [comment]
Also is there any way to ignore some module like the versioneer module?

**Comment by FlorianWilhelm** [comment]
Hi @enfeizhan, thanks for reporting. I can confirm your two issues. PyScaffold aktuelle uses PBR for this functionality. A workaround is to delete ``docs/api`` before rebuilding the docs. Regarding your exclusion of files question have a look here: http://docs.openstack.org/developer/pbr/#pbr

**Comment by FlorianWilhelm** [comment]
Could you try activating ``autodoc_index_modules = True`` in your ``setup.cfg`` and see if that helps with new module files? In this case PBR will itself generate the api docs.

**Comment by FlorianWilhelm** [comment]
I added following bug report in PBR https://bugs.launchpad.net/pbr/+bug/1647140

**Comment by enfeizhan** [comment]
Hi @FlorianWilhelm,
   Thanks a lot for the detailed reply. I tried your recommendations. It seems only deleting ``docs/api`` works.

  What I just did was, (I have found another workaround by manually adding or removing items in ``docs/api/myproject.rst``) first I turned ``autodoc_index_modules`` on and did ``python setup.py docs`` again. I expected I would see the modules I have manually removed from ``docs/api/myproject.rst`` appear again, but they didn't.
  Then I removed ``docs/api`` completely, this time the then removed module did appear.
   Lastly I tried to exclude them from ``autodoc_exclude_modules`` as in the openstack tutorial. Unfortunately the syntax is unclear to me so I am not sure if I have done it correctly so the modules I want to exclude are still there.

**Comment by FlorianWilhelm** [comment]
Hi @enfeizhan, I created a project ``test_proj`` with files `new_module1-3.py` including in ``setup.cfg``:
```
[pbr]
# Let pbr run sphinx-apidoc
autodoc_tree_index_modules = True
autodoc_tree_excludes = test_proj/new_module2.py test_proj/new_module3.py
# Let pbr itself generate the apidoc
# autodoc_index_modules = True
# autodoc_exclude_modules = ...
# Convert warnings to errors
# warnerrors = True
```
and it works for me as expected, i.e. only ``new_module1.py`` is indexed.

**Comment by enfeizhan** [comment]
Danke @FlorianWilhelm. I'll try it out soon.

**Comment by FlorianWilhelm** [comment]
Since PBR will be dropped with version 3 of PyScaffold, we are now able to control the behaviour manually inside `conf.py`. I did this in a way that solves this issue.
